---
SelfBalancingLogarithmPCACalculatorConfig:
  logarithm_smoothing_term: 1.e-10
  logarithm_transform: true
  max_rows: null
  n_components: 1
  pca_default_weights: [1, 2, 1, 2, 5, 3, 1, 1]
  score_columns: [pxtr_1, pxtr_2, pxtr_3, pxtr_4, pxtr_5, pxtr_6, pxtr_7, pxtr_8]
  target_distribution_mean: 0.5
  total_score_column: total_score
  upper_bound_3sigma: 1
  var_normalized: false
